.github/workflows/scan-images.yml

1. Add a GitHub action workflow which runs once a month on all active images and will run a vulnerability scan on the image.
To advise on security of images we ship.
1. Report to the security channel
2. Update the security info on the repository
```sh
act --container-architecture linux/amd64 workflow_dispatch -j list-tags -j scan-job
```

CP-20087 add continuous image scanning

---

pkg/cmd/config/command.go
pkg/cmd/config/command_test.go
pkg/cmd/config/internal/scrape_config.tmpl
pkg/k8s/services.go
pkg/k8s/services_test.go

This PR modifies the `generate` command to update the Service Endpoints for both Node Exporter and KSM.
**Testing**
The updated command and it's output:
``` bash
cloudzero-agent-validator git:(cp-21861) ./bin/cloudzero-agent-validator config generate --kubeconfig /tmp/bdren.kubeconfig --account 123 --cluster test --region us-east-1 --namespace default --configmap cz-prom-agent-configuration --pod cz-prom-agent-cloudzero-agent-server-5b54bdfbbc-b9xgk
```
``` yaml
Name:         cz-prom-agent-configuration
Namespace:    default
Labels:       <none>
Annotations:  <none>
Data
====
prometheus.yml:
----
global:
scrape_interval: 1m
scrape_timeout: 10s
scrape_protocols:
- OpenMetricsText1.0.0
- OpenMetricsText0.0.1
- PrometheusText0.0.4
evaluation_interval: 1m
scrape_configs:
- job_name: …
```

CP-21861: Modify Generate Command to Update Pod ConfigMap with Service Endpoints

---

pkg/cmd/config/command.go
pkg/cmd/config/command_test.go
pkg/k8s/services.go
pkg/k8s/services_test.go

This was a small miss #33, essentially we need to use the argument `namespace`, rather than `"default"`.

[CP-21861 (part-2)]: Use Namespace Arguement

---

pkg/cmd/config/command.go
pkg/cmd/config/command_test.go

This PR modifies the `generate` command by allowing users to include the path to their secret. 
The value originates from: https://github.com/Cloudzero/cloudzero-charts/blob/develop/charts/cloudzero-agent/templates/cm.yaml#L162

CP-21862: Generate Command should Allow users to specify CloudZero Secret File Path

---

.github/workflows/docker-build.yml

I changed `latest=auto` to `latest=false` based on the docs [here](https://github.com/docker/metadata-action/tree/8e5442c4ef9f78752691e2d8f8d19755c6f78e81/?tab=readme-ov-file#flavor-input), with the thinking that we don't want this to be handled by this build step
testing on my fork in progress

CP-22291: remove latest tag in build

---

pkg/cmd/config/command.go
pkg/cmd/config/command_test.go
pkg/k8s/services.go
pkg/k8s/services_test.go

This PR modifies the `generate` command to search for KSM in _all_ namespaces. Additionally, if KSM is not found by searching for the substring in the Service name iteself, the command checks the Service's Labels for `"app.kubernetes.io/name": "kube-state-metrics`, which should be more robust.

CP-22509: Search All Namespaces for KSM and Improve Search Logic

---

pkg/diagnostic/catalog/catalog_test.go
pkg/diagnostic/kms/check.go
pkg/diagnostic/kms/check_test.go
pkg/diagnostic/runner/runner_test.go

This PR modifies the `kube_state_metrics_reachable` `post-start` job to also validate that all CloudZero KMS metrics are available. A sample log output from the Job:
``` json
{
"level": "info",
"log_sequence": 6,
"msg": "Using endpoint URL: http://192.168.5.249:8080/metrics",     <---- Internal IP discovered using the Service Endpoint 
"op": "ksm",
"time": "2024-11-25T08:23:44Z"
}
{
"level": "info",
"log_sequence": 7,
"msg": "All required metrics found: [kube_pod_info kube_node_info]",                <---- Metric Check (subset for now)
"op": "ksm",
}
```
``` bash
Part of the Cluster Status Report related to KMS produced by the Job: {\"name\":\"kube_state_metrics_reachable\",\"passing\":true}]}",
```
The log statements show that the job was able to discover the internal IP of the KSM …

CP-23050: Validate CloudZero Metrics are available from Kube State Metrics

---

pkg/config/prometheus.go
pkg/config/prometheus_test.go
pkg/config/testdata/cloudzero-agent-validator.yml
pkg/diagnostic/kms/check.go
pkg/diagnostic/kms/check_test.go

**Description**
This PR modifies the `kube_state_metrics_reachable` command by including the full list of KSM metrics passed by the chart, rather than the hardcoded subset used during testing.
Accompanying Chart changes: https://github.com/Cloudzero/cloudzero-charts/pull/115
**Testing**
Below is the output of the CloudZero Agent Server `post-start` job. If you notice, the logs outline the metrics being validated, eventually leading to a passing status for `kube_state_metrics_reachable`:
``` json
{
"level": "info",
"log_sequence": 1,
"msg": "Using endpoint URL: http://cloudzero-state-metrics.prom-agent.svc.cluster.local:8080/metrics",
"op": "ksm",
"time": "2024-12-03T21:52:29Z"
}
{
"level": "error",
"log_sequence": 2,
"msg": "Failed to fetch metrics on attempt 1: Get …
```

CP-23740: Use Required KSM Metrics From Chart when Validating KSM

---

pkg/diagnostic/kms/check.go

This PR adds some additional logging to output reach required KSM metric as it's found in the response body.

CP-23740: Log Each Required KSM Metric

---

.github/workflows/mirror-chart.yml

This will automatically mirror any changes in helm/ on the develop branch over to the develop branch of the cloudzero-charts repo.
This is one of those things that is somewhat difficult to test, but I've done what I can by pushing to a fork of the cloudzero-charts repo and it worked well.

CP-27087: mirror Helm Chart to cloudzero-charts

---

DEVELOPMENT.md

@evan-cz @roberthocking This is a small update to the development documentation for the repo after I ran through building it.
It turns out that the `develop` branch isn't protected, as I accidentally pushed this straight to `develop` when I though I was on a small branch, but I reverted that, and it is in this PR now.

Minor dev documentation update

---

helm/templates/aggregator-deploy.yaml
helm/templates/deploy.yaml
helm/templates/init-job.yaml
helm/templates/insights-deploy.yaml
helm/values.yaml

Users might have some interesting DNS requirements (e.g. Wise). This allows them to override the `dnsConfig` and `dnsPolicy` without directly modifying the chart. 
Defaults are defined [as per Kubernetes documentation](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy).

Chart: Add dnsPolicy and dnsConfig configurables to deployment/job specs

---

Makefile
cmd/agent-validator/main.go
docker/Dockerfile
helm/templates/deploy.yaml
helm/templates/insights-deploy.yaml
helm/values.yaml
pkg/cmd/install/command.go
scripts/ci-checks.sh

Previously, we were relying on a bit of scripting to copy the agent-validator over to an emptyDir that could be used in the Prometheus image. However, since we are now basing everything off a scratch image that doesn't have a shell (or `cp` for that matter) installed that no longer works.
This adds an `install` command to the `cloudzero-agent-validator` image, which will copy itself to the provided destination, and alters the Helm chart to use that instead of `/bin/sh` and `cp`.
This also sneaks in a few other useful bits:
* Adds `package-debug` and `package-build-debug` make targets to build debug images (which do contain /bin/sh and cp)
* Adds a check to `scripts/ci-checks.sh` to make sure there is somewhere in the Helm chart that we know how to update for releases in order to ensure we …

CP-27884: fix agent-validator initialization

---

helm/Chart.yaml
helm/templates/_cm_helpers.tpl
helm/templates/aggregator-deploy.yaml
helm/templates/cm.yaml
helm/templates/insights-deploy.yaml

testing:
1. asserted that changing a shared config (region) rolls both aggregator and webhook server pods
2. asserted that changing only an insightController setting only rolls the webhook-server pod
3. asserted that changing only an aggregator setting only rolls the aggregator pod
4. asserted that changing a non insightsController or aggregator config does not roll pods
5. asserted that additional pod annotations can still be added

CP-27962: webhook server and aggregator deploys roll on config change

---

helm/templates/cm.yaml
helm/templates/init-job.yaml
helm/templates/webhooks.yaml

testing:
1. disabling labels and annotations results in no webhooks
```yaml
labels:  
enabled: false
annotations:  
enabled: false  
```
```bash
helm template cloudzero-agent -n cloudzero-agent --create-namespace ./ --set foo=bat -f ~/dmepham/testing/integration-test-cluster.yaml   | grep 'kind: ValidatingWebhookConfiguration' || echo 'test passed'
test passed
```
also asserted that installing brought up resource correctly, including the init-cert job
2. default true resources (namespaces) are not created when set to false
```yaml
labels:  
enabled: true
resources:
pods: true 
namespaces: false
deployments: true
annotations:  
enabled: false  
```
```bash
helm template cloudzero-agent -n cloudzero-agent --create-namespace ./ --set foo=bat -f ~/dmepham/testing/integration-test-cluster.yaml …
```

CP-26601: users should be able to disable default on webhooks

---

.github/workflows/release-to-main.yml

This is pretty straightforward; in the release-to-main workflow we check for "-beta-" in the name to look for prereleases. This just makes it also check for "-rc-".

CP-28103: treat RCs as pre-releases in release-to-main workflow

---

.github/workflows/release-to-main.yml

Fix path for helm release note check since it is not under `helm`
- He has taught old dogs a variety of new tricks, live dangerously my friend

Fixed path for release note check

---

app/functions/collector/main.go
app/functions/shipper/main.go
helm/templates/aggregator-deploy.yaml
helm/templates/cm.yaml
helm/values.yaml

- Modification of the Prometheus agent config to use `kubernetes_sd_configs` to source all instances of the collector/shipper
- Add port configs to the containers in the aggregator pod
- Expose the Prometheus endpoint for the shipper
Config:
```
host: dev-api.cloudzero.com
apiKey: ...
clusterName: jake-dev-cluster-aws
cloudAccountId: 3bf91910396d9cf94bd951095e1e1ca9
region: us-east-1
components:
agent:
image:
repository: ghcr.io/cloudzero/cloudzero-agent/cloudzero-agent
tag: t-2f55bbb5ea52fd11497bf81e6fcdeb0f
insightsController:
server:
replicaCount: 3
logging:
level: trace
aggregator:
replicas: 2
logging:
level: trace
database:
purgeRules:
lazy: false
emptyDir:
enabled: true
sizeLimit: "15Gi"
```
Prometheus service:

CP-28084: scrape all instances of collector and shipper

---

helm/values.yaml

There are now a lot of global configuration properties for setting stuff such as labels, annotations, dns configuration, etc. in our chart. Unfortunately, these aren't plumbed through to the kube-state-metrics subchart. The initial goal of this was to automatically plumb everything through, but sadly Helm is not cooperative so this ended up as just a documentation thing :(
This is the configuration for the kube-state-metrics Helm chart, which unfortunately cannot be controlled via templates (it's a known problem in Helm, with attempted solutions going back many years, but no resolution as of today). Therefore, I've adjusted the documentation for several properties (annotations, priorityClassName, etc.) to also inform people that they'll likely need to set those values in kubeStateMetrics …

CP-28107: document kubeStateMetrics

---

.github/pull_request_template.md
.github/workflows/docker-build.yml
.github/workflows/test-matrix-k8s-k3s.yaml

> This awesome thing improves my smile brightness
This will make it possible for other workflows to reference the development image, even though it has not been pushed anywhere.
> Outline the actions you took to achieve a brighter smile
Adds steps to create a build artifact from the docker image.
> Instructions to reproduce what I did to test this and achieve a brighter smile
It runs. However this has to get merged before it can be used by other workflows.

Save the image for 'workflow_run' support

---

app/config/gator/settings.go
app/config/gator/settings_test.go
app/config/validator/diagnostics_test.go
app/domain/backfiller/backfiller.go
app/domain/housekeeper/housekeeper.go
app/domain/pusher/pusher.go
app/domain/shipper/errors_test.go
app/domain/shipper/shipper_integration_test.go
app/functions/insights-controller/main.go
app/handlers/profiling_test.go
app/handlers/prom_metrics_test.go
app/http/middleware.go
app/logging/filtered_writer_test.go
app/logging/instr/span_test.go
app/storage/core/baseimpl_test.go
app/storage/disk/metric_file_test.go
app/types/metric_test.go

A smaller PR to add some new tests to things that were not covered before. I think we should strive for 75% of code coverage as an arbitrary minimum, but this is not a good benchmark to die on. 
Also, a fair amount of our code is also tested in the `tests/smoke` directory, which is not going to report on go test coverages. This just addresses some of the more obvious scenarios and did a deeper dive into what is and not tested.
In addition, some log fields were converted from snake case to cammel case

CP-22715: improve testing coverage

---

.github/workflows/golang-ci.yml
.prettierignore
Makefile
tests/helm/template/manifest.yaml
tests/helm/template/overrides.yaml

This adds a target to the Makefile to automatically regenerate a manifest as part of the `generate` Make target. The output goes to tests/helm/template/manifest.yaml, which is checked into the repo.
The purpose of this change is to make sure that every change to the output of the Helm chart is intentional; if you alter the Helm chart without a corresponding alteration of the generated output, a status check should fail. Due to the fact that the manifest is included in the repo, the effect of the changes should be apparent in the commit, and will be easy to notice during a PR review if not sooner.
I also refactored the Helm portion of the Makefile a little bit to extract some flags into a common variable, and switched to using a GitHub Action to install protoc instead of using apt so we …

CP-28160: add Helm template generation test

---

helm/values.schema.json

Improve validation for clusterName to support additional characters
updated clusterName validation so we can accept _ as part of the clusterName
ran 2 tests 1 before with clusterName of "cluster_name" it failed (as expected)
ran again after change and it worked as expected

CP-28376 added _ as a valid character for clusterName

---

helm/templates/_helpers.tpl
helm/templates/aggregator-deploy.yaml
helm/templates/deploy.yaml
helm/templates/insights-deploy.yaml
helm/values.yaml
tests/helm/template/manifest.yaml

Support for setting a pod disruption budget for all our deployments.
This also bumps the default replica count for the gator from 1 to 3, and moves the setting to `.Values.components.aggregator.replicas`. Similarly, `.Values.insightsController.server.replicaCount` moves to `.Values.components.webhookServer.replicas`, though if the former is set it will be used (preserving BC isn't an issue for the gator since we haven't had a release yet)
Lots of tweaking the values and looking at the `helm template` output. Also set couple values and did a deployment.

CP-28054: add option for setting pod disruption budgets

---

helm/Chart.yaml
helm/values.yaml
tests/helm/template/manifest.yaml

For security best practices, we need to stay current with prometheus agent
Bump prometheus agent version
Deployment testing

CP-28539: bump version of prometheus image

---

app/config/gator/settings.go
app/functions/collector/main.go
app/storage/disk/disk.go
app/storage/disk/disk_test.go
helm/templates/_cm_helpers.tpl
helm/values.yaml
tests/helm/template/manifest.yaml
tests/smoke/client_test.go
tests/smoke/collector_test.go
tests/smoke/load_test.go

This allows us to set the rotation interval independently for Cost and Observability metrics.
The latter are lower-priority and can probably wait longer, but we generally want to get the cost metrics shipped to the CloudZero server much more quickly.
`make test` has some tests which rely on the setting. I also deployed to a cluster to verify the Helm changes. Just to make extra sure the settings were being picked up, I also added some logging to the DiskStore (locally, not in the patch) to dump the interval being used and verified that it corresponded to the relevant setting.

CP-28109: separate config for cost and o11y metrics rotation interval

---

helm/README.md
helm/values.yaml

We have a warning for users to not use a wildcard so that they don't hit the 300 tag limit. This PR puts it in places that the user may be more likely to see
- Adds a warning text in the values.yaml and the example yaml in the README
- 
N/A

CP-28547: add label warning in more locations

---

app/domain/shipper/shipper.go

@roberthocking pointed out an error where in some cases where the shipper restarts (but the pod does NOT restart), then there would be an error for a directory already created in the emptyDir.
Changing `Mkdir` to `MkdirAll` fixes this. If the directory already exists then it will just return null. In addition, I did a quick check throughout to ensure we are not making this mistake anywhere else. This was the only occurrence, so it must have slipped through the cracks. potentially we should all K8s tests to restart individual containers within the pod and ensure we get no error logs.

changed mkdir to mkdirall to fix create dir error

---

.github/workflows/test-matrix-k8s-k3s.yaml
helm/Chart.yaml

To support older clusters.
Reduce Kubernetes dependency from 1.23 to 1.21, add 1.21 and 1.22 to the test matrix.
Mostly relying on the test matrix here...

CP-28707: reduce Kubernetes dependency to 1.21

---

.github/workflows/docker-build.yml
.github/workflows/golang-ci.yml
.github/workflows/test-matrix-k8s-k3s.yaml
.github/workflows/test-matrix-replicated-k8s-clusters.yaml
tests/testkube/tests.yaml

> This awesome thing improves my smile brightness
- This tests a bunch of different types of Kubernetes cluster, including `eks`, `gke`, `aks`, and `rke2` (Rancher - which should be useful since people do run Rancher clusters in these cloud providers).
-  Today, it is also possible to add support for `oks` (Oracle), `okd` (OpenShift) , `k3s`, and `kind`, but these do not really do us any good, so let's not waste the money.
- It also adds tests for `arm64` based systems, in addition to the default `amd64` based systems.
- And it also refactors the Docker build workflow to speed it up by using native runners for `arm64` images.
> Outline the actions you took to achieve a brighter smile
A new github workflow.
> Instructions to reproduce what I did to test this and achieve a brighter smile …

Replicated test matrix workflow

---

.github/workflows/docker-build.yml

> This awesome thing improves my smile brightness
by limiting the replicated tests, so that they only run when a PR has been added to a merge queue or there is a push directly to develop or main.
> Outline the actions you took to achieve a brighter smile
Taking advantage of the merge queue support for GitHub Enterprise customers.
> Instructions to reproduce what I did to test this and achieve a brighter smile
By creating this PR...

Limit replicated to merge Qs & critical pushes

---

helm/values.yaml

Documentation helps customers, as well as us, understand what everything is for.
I was also able to remove a few pieces that we no longer reference, but for the most part this is just about documenting as much stuff as I could.
N/A; documentation-only change.

CP-27295: add documentation for most stuff in values.yaml

---

helm/templates/_cm_helpers.tpl
tests/helm/template/manifest.yaml

When using ArgoCD, due to the schema validations -- AWS account ID which is a numeric value is asserted as a string since Helm will put it in scientific notation format - which prevents proper matching the actual account ID.
In practice we have seen multiple approaches, and many times users add extra quotes (double and single) to work around the differences in the schema versus ArgoCD issues.
This PR Cleans input strings before use using the method previously defined for this purpose.
1. Apply the cleanString to the values before use
1. Use junk values as follows
```yaml
cloudAccountId: -|
'"975482786146"''
clusterName: aws-cirrus-jb-cluster
region: us-east-2
existingSecretName: cloudzero-api-key
host: dev-api.cloudzero.com
commonMetaLabels:
cloudzero.com/component: cloudzero-agent …
```

CP-28953: clean input strings

---

Makefile
tests/helm/template/manifest.yaml

Helm defaults to the same namespace that kubectl is set to use as the default. Previously, we had assumed that would be the "default" namespace, but that assumption doesn't hold true on everyone's machines, and we shouldn't rely on it.
Explictly pass a namespace (`$(HELM_TARGET_NAMESPACE)` in the Makefile) so the local kubectl configuration won't matter.
This does create a lot of noise since we're moving from the "default" namespace to "cz-agent", but it should be more robust against future changes.
Run `make helm-generate-tests`

CP-29000: pass namespace to Helm when regenerating manifest

---

.github/workflows/cleanup-daily.yml
.github/workflows/docker-build.yml
app/types/status/cluster_status.pb.go
app/types/status/cluster_status.proto
app/types/status/report.go

> This awesome thing improves my smile brightness
This primary reverts the GitHub status action fork back to a specific git ref. However, it also pulls out the GHCR image cleaning step into it's own scheduled workflow as it take many minutes to run.
> Outline the actions you took to achieve a brighter smile
Mostly did a lot of testing a debugging in https://github.com/spkane/commit-status-updater/tree/merge-group-support
> Instructions to reproduce what I did to test this and achieve a brighter smile
Tested via a previous merge that was failing tests, but is now passing. Merging this will provide a secondary/confirmation test.

merge group work

---

.github/workflows/docker-build.yml

This should resolve them running twice when being merged.

Fine-tuning when container images are built and tested

---

helm/templates/webhook-certificate.yaml

ArgoCD apparently has trouble with the durations not including hours/minutes, which results in it always thinking there is a diff between what is applied and what is installed.
Personally, I didn't do anything. But @ddemaret-plaid was kind enough to supply a patch to add hours/minutes to the relevant fields in the chart, in #227. I'm only opening this because of a permissions issue with GitHub Actions preventing the container image from being pushed to GHCR during the build.
Change is effectively a no-op from our perspective.
Closes #227

CP-29026: update duration and renew of certificate to include minutes

---

helm/docs/upgrades.md

These annotations were necessary in days of yore, when we had a `ttlSecondsAfterFinished` on the jobs. However, we removed that a while back in favor of just giving each job a unique name derived from a hash of the configuration version. With that change, the jobs are run whenever the configuration is updated without relying on the cluster to delete the old jobs.

CP-29129: remove obsolete section on ArgoCD

---

app/domain/metric_collector.go
app/http/middleware/middleware.go

This fixes a few papercuts in the logging code in the collector. Namely:
1. No longer log HTTP requests to /healthz and /metrics at debug level; only log them at trace.
2. Include the address of the client in the logs. This is especially useful for daemonset mode to make sure the cAdvisor metrics are coming from each node.
3. Include the count of which metrics we're receiving each time we receive new metrics. This is only computed if the log level is set to debug or trace, so it shouldn't have any performance impact in the standard deployment.
`make package-debug`, deploy it to a cluster. Then do something like `kubectl -n cza logs -f pod/cz-agent-aggregator-68d48f8559-tdvgq | jq .`, sit back and enjoy your new, more useful logs :)

CP-29130: logging improvements in collector

---

.github/dependabot.yml

To keep our Helm dependencies (currently only kube-state-metrics) up-to-date.
Add /helm/ ecosystem to our Dependabot configuration.
Completely untested. YOLO!

CP-28622: add Helm to Dependabot configuration

---

.github/workflows/golang-ci.yml

A few of our Go tests are a bit flaky. Normally this isn't a major problem since it's pretty straightforward to re-run the failed tests, and honestly it's a good reminder to fix those flaky tests.
However, with the merge queue this is extremely annoying, since if *any* test fails it gets kicked out of the queue and we have to re-add it manually, at which point it runs *all* the tests again.
So I thought it might be a good idea to tweak the CI setup a bit so that, if we're running in the merge queue, `make test` failures will simply be re-run (up to thrice). However, if we aren't in the merge queue only make a single attempt.
Hopefully this becomes less important as time goes on and we are able to fix these tests, but in the meantime this should be quite useful.
By letting the action run. …

CP-29051: if Go tests fail in the merge queue, rerun them

---

helm/templates/_cm_helpers.tpl
tests/helm/template/federated.yaml
tests/helm/template/manifest.yaml

When looking at a recent customer issue, I thought there was a possibility that it was related to the Prometheus configuration, so I started looking at the configuration to understand it. As part of the process of figuring out how it worked, I decided to just document it in-place.
Once I was doing that, I noticed that there were also a lot of properties we were setting to the same values as the defaults, which was just creating a lot of extra complexity and cognitive load.
This adds a lot of documentation to the configuration, which honestly should make things a lot easier on us (well, at least me) in the future when we need to work on the configuration. It also removes properties which needn't be set as they are already the defaults.
Deploying and verifying that we're still getting all …

CP-29248: clean up and document Prometheus config

---

helm/templates/config-map.yaml
tests/helm/template/federated.yaml
tests/helm/template/manifest.yaml

This is useful information to have for debugging purposes. Eventually we may want to automatically send this to CloudZero's servers, but for now this just provides an easy place to extract the configuration from.
Added a ConfigMap to store the chart configuration.
Note that I have masked the `apiKey` if it is set, but everything else should appear as-is.
With the JSON Schema stuff the risk of anyone accidentally including sensitive information elsewhere should be somewhat diminished.
Mostly relying on the generated manifests for this one, since we aren't actually using this for anything right now.

CP-29363: store configuration values in a ConfigMap

---

helm/README.md

Users often ask about why we need a `ValidatingWebhookConfiguration`, and they often experience issues when using `NetworkPolicies` that deny traffic from the API server to the agent components. This documentation should help with that.
We were also missing a requirement regarding egress traffic to s3 endpoints.
Added documentation to the README
N/A

CP-29472: Add documentation for use of ValidatingWebhookConfiguration, s3 egress requirement

---

app/functions/helmless/README.md
app/functions/helmless/root.go

This provides us with a relatively easy way to find non-default configuration, which is invaluable for debugging.
Added a tool which basically diffs the default configuration (`helm show values ./helm`) and the configured values (retrieved from a ConfigMap), outputting it as a minimal overrides.yaml file which can be used to achieve the same result, without all the noise of setting values to the defaults.
There are instructions in the README. Note that you'll need a pretty recent deployment of the Helm chart in order to follow them, since the ConfigMap containing the configured values was only recently added.

CP-29437: add tool to show differences between configurations.

---

app/config/gator/settings.go
app/domain/metric_collector.go
app/handlers/remote_write.go
helm/templates/_cm_helpers.tpl
helm/values.schema.json
helm/values.schema.yaml
helm/values.yaml
tests/helm/template/federated.yaml
tests/helm/template/manifest.yaml

When Prometheus sends data to the Collector, it uses the standard Go HTTP client library, which reuses the connection as an optimization.
Unfortunately, the round robin to distribute the load across the k8s service happens when the initial connection is made, and since in non-federated mode we really only receive data from Prometheus and the Webhook server, which means we just have two things that create an initial connection, then always send data over those connections.
Luckily, and somewhat surprisingly (at least to me), Prometheus seems to be using HTTP/1.1 to send the data, which means we can just add a Connection: close periodically to get it to close the connection and go through the load balancing again.
This will randomly (according to a configurable probability) add a …

CP-29585: periodically close HTTP connections

---

app/functions/shipper/main.go

We want to be able to access pprof data on the shipper.
Make the shipper obey the (existing) `profiling` flag.
Deploy, then something like `kubectl -n cza port-forward pod/cz-agent-aggregator-67b58d99d8-vxzgb 8081:8081` to port forward to the HTTP server on the shipper, then point your browser at http://localhost:8081/debug/pprof/

CP-29610: add /debug/pprof/ endpoint to shipper when profiling enabled

---

helm/templates/aggregator-deploy.yaml
helm/values.schema.json
helm/values.schema.yaml
helm/values.yaml
tests/helm/template/federated.yaml
tests/helm/template/manifest.yaml

Previously, the annotations on the aggregator would only use the default annotations. Customers would like to be able to provide annotations specific to the Aggregator.
This was a change requested by @moensch in Cloudzero/cloudzero-charts#205, thanks @moensch!
Created a `components.aggregator.annotations`, which is added to the `defaults.annotations` when writing the Aggregator's annotations in the template.
Added an annotation to my overrides, checked to make sure it appeared in the output.

CP-29618: support setting aggregator-specific annotations

---

.github/dependabot.yml

SOC 2 compliance.
Add a hard-coded Jira issue to every dependabot PR. I think it technically checks the box for SOC 2, so better than nothing even if a bit silly...
Mostly have to wait for Dependabot to run 🤷. It does make it through the dependabot-validator CI check, though.

CP-29684: add Jira issue prefix to dependabot PRs

---

helm/templates/agent-cm.yaml
helm/values.schema.json
helm/values.schema.yaml
helm/values.yaml
tests/helm/template/federated.yaml
tests/helm/template/manifest.yaml

We are occasionally seeing errors from Prometheus: "Error on ingesting out-of-order samples". We haven't had much luck reproducing the issue, but based on some searches we're hoping this provides a way to get rid of them.
This provides an easy way to configure the `out_of_order_time_window` property for Prometheus, and sets it to 5m by default.
Install the Helm chart to make sure it doesn't break anything. Whether it fixes the issue or not, we're not sure yet. Hence a draft PR for now.

CP-29055: add support for setting Prometheus out_of_order_time_window

---

.github/workflows/release-to-main.yml

The release-to-main workflow is currently failing because `make helm-generate-tests` now requires gojq, which isn't installed in this workflow.
This patch just installs go, then runs `make install-tools` prior to `make helm-generate-tests`
YOLO.

CP-29706: install tools to resolve dependency on gojq in release-to-main

---

.github/workflows/release-to-main.yml

I'm not entirely sure why, but `make` detects that helm/values.schema.json needs to be regenerated when running in CI. This is handled automatically in the Makefile, but reformatting the result (using prettier) is not.
Since we should already have prettier installed due to the `install-tools` target, we can just add the `format` target when running `helm-generate-tests` and reformat the output before committing. This should basically turn the regeneration of the JSON schema into a no-op, but without the release-to-main workflow will fail due to uncommitted changes in `helm/values.schema.json`.
Touch `helm/values.schema.yaml` so `helm/values.schema.json` gets regenerated, then run the commands in the release-to-main workflow. Note that the sed on macos won't work, but if you've installed …

CP-29706: run `format` make target after regenerating manifests

---

app/domain/shipper/shipper.go
app/storage/disk/disk.go

Currently the collector and shipper are completely silent during normal operation at the (default) info log level. It would be nice to just be able to see a bit of activity in the logs so we know things are working...
Just adds a log entry on the collector side when we flush to disk, and bumps an existing log message from debug to info level on the shipper side.
Deploy, then `kubectl logs`

CP-29742: emit logs periodically from the collector and shipper

---

.dockerignore
Makefile
app/functions/helmless/README.md
app/functions/helmless/default-values.yaml
app/functions/helmless/root.go
docker/Dockerfile
helm/templates/_helpers.tpl
helm/templates/helmless-cm.yaml
helm/templates/helmless-job.yaml
tests/helm/template/federated.yaml
tests/helm/template/manifest.yaml

This provides an easy way to get the minimal config overrides.
Create a job which runs helmless against the values in the configmap. I also renamed the config-values configmap to helmless-cm, since it is only used by helmless-job and that matches our naming convention a bit better.
Deploy, then `kubectl -n whatever logs --tail 9999 -l app.kubernetes.io/component=helmless`

CP-29759: add helmless job

---

helm/values.schema.json
helm/values.schema.yaml
tests/helm/schema/server.serviceAccount.name.invalid.fail.yaml
tests/helm/schema/server.serviceAccount.name.valid.pass.yaml

This is an old, deprecated way to set the service account name, but it is still supposed to be viable (until 2.0) so we should allow it in the schema.
Allow setting server.serviceAccount.name in the JSON schema
Tests are included in the PR.

CP-29885: allow setting server.serviceAccount.name in JSON schema

---

.golangci.yaml
app/domain/shipper/utils.go
app/domain/webhook/handler/generic_handler_test.go

We were comparing expected values against expected values, so the test was a noop.
Fixed the comparisons to compare expected vs result. This unmasked some issues in the test vectors, which I also fixed.
I tried adding a couple of linters to help spot this type of thing in the future, but alas nothing can detect if the arguments to reflect.DeepEqual or cmp.Diff are the same values... Might be a fun project to write a linter for that in the future.
`make test`

CP-29878: don't test values against themselves in generic handler tests

---

helm/templates/_helpers.tpl
tests/helm/template/federated.yaml
tests/helm/template/manifest.yaml

Previously, we were merging the into the default values for the components, which was causing the values to be set in the configuration instead of relying on the defaults, which was causing Helmless to always include them.
Merge into a deepCopy instead.
The generated manifests show the difference.

CP-29876: don't overwrite default values when generating PDBs

---

helm/templates/_helpers.tpl
helm/templates/agent-cm.yaml
helm/templates/agent-daemonset-cm.yaml
helm/templates/agent-pvc.yaml
helm/templates/agent-serviceaccount.yaml
helm/templates/aggregator-secret.yaml
helm/templates/backfill-job.yaml
helm/templates/init-cert-job.yaml
helm/templates/validator-cm.yaml
helm/templates/webhook-certificate.yaml
helm/templates/webhook-cm.yaml
helm/templates/webhook-deploy.yaml
helm/templates/webhook-validating-config.yaml

The `merge` function in Helm will write to the destination parameter (the first parameter), so if we just pass the defaults directly and merge into them, we will end up adding the values for the component we're merging to the defaults.
Instead, we use the `deepCopy` function to create a copy of the defaults, then merge into that.
`make helm-generate-tests` to make sure I didn't break anything, and creating overrides to set the component-specific stuff and make sure it doesn't clobber the defaults for other components.

CP-29491: don't clobber defaults when merging component-specific config

---

.github/workflows/test-chart.yml
.gitignore
Makefile
go.mod
go.sum
helm/templates/_helpers.tpl
helm/templates/webhook-service.yaml
tests/helm/schema/defaults.dns.valid.pass.yaml
tests/helm/template/cert-manager.yaml
tests/helm/template/federated.yaml
tests/helm/template/manifest.yaml
tools.go

Previously, there was a bug in the template which was causing the generated output to not be valid according to the Kubernetes schema. I want to be able to catch bugs like this automatically.
For every schema test where the result is valid (i.e., files named *.pass.yaml), run the output through kubeconform with strict validation enabled.
The schema tests are a great opportunity because they exercise a lot of different properties, particularly ones which don't get used very often. This gives us much greater coverage. In fact, I was able to spot several issues using these new tests, so this PR also includes fixes for those.
I also added a GitHub Action job to run `helm -j helm-test`. Oh, and that `-j` is interesting; I refactored the Makefile a bit to create multiple targets, so -j will …

CP-30020: add kubeconform tests

---

helm/docs/releases/1.2.2.md

So we can release 1.2.2.
Add release notes for 1.2.2.
`test -f helm/docs/releases/1.2.2.md`

CP-30015: add release notes for 1.2.2

---

helm/docs/releases/1.2.2.md
helm/templates/_defaults.tpl
tests/helm/template/cert-manager.yaml
tests/helm/template/federated.yaml
tests/helm/template/manifest.yaml

Be the resource_type and workload labels, which are emitted by the webhook server.
Add "resource_type" to the list of allowed labels.
YOLO.

CP-30042: allow resource_type and workload labels in Gator

---

app/functions/helmless/default-values.yaml
helm/docs/istio.md
helm/templates/webhook-deploy.yaml
helm/values.schema.json
helm/values.schema.yaml
helm/values.yaml
tests/helm/schema/insightsController.server.podAnnotations.with.suppressIstioAnnotations.pass.yaml
tests/helm/schema/insightsController.server.suppressIstioAnnotations.false.pass.yaml
tests/helm/schema/insightsController.server.suppressIstioAnnotations.invalid.fail.yaml
tests/helm/schema/insightsController.server.suppressIstioAnnotations.true.pass.yaml
tests/helm/template/cert-manager.yaml
tests/helm/template/federated.yaml
tests/helm/template/manifest.yaml

Previously, users deploying cloudzero-agent in Istio-enabled clusters had to manually configure `sidecar.istio.io/inject: "false"` annotations to prevent Istio sidecar injection from interfering with webhook TLS communication. This created a poor out-of-the-box experience and required users to read documentation and troubleshoot connectivity issues.
This change makes the webhook server work automatically in Istio environments by adding the `sidecar.istio.io/inject: "false"` annotation by default. The webhook server pods now automatically include this annotation without any user configuration required.
The implementation adds a new
`insightsController.server.suppressIstioAnnotations` boolean property (default: false) that controls whether the automatic annotation is added. When false …

CP-30109: add automatic Istio sidecar injection suppression for webhook server

---

app/functions/helmless/default-values.yaml
helm/templates/webhook-validating-config.yaml
helm/values.schema.json
helm/values.schema.yaml
helm/values.yaml
tests/helm/template/cert-manager.yaml
tests/helm/template/federated.yaml
tests/helm/template/manifest.yaml

reduces the impact of potential timeout issues with the webhook server
allow the user configure the timeout, with a default of 1 second
in progress

CP-29473: reduce webhook timeout, allow configuration of value

---

app/config/gator/settings.go
app/config/validator/deployment.go
app/config/webhook/settings.go
app/utils/scout/detect_configuration.go
app/utils/scout/detect_configuration_test.go

The agent wasn't providing visibility when manually configured values differed from auto-detected cloud environment settings. This made it difficult to debug deployment issues where operators had specified incorrect regions, account IDs, or cluster names that didn't match the actual environment.
This patch tweaks DetectConfiguration to always run scout detection and emit structured warning logs when provided values don't match what's detected. The function now compares all provided values against detected ones and logs specific warnings for each mismatch, making it much easier to spot configuration problems.
There are several new tests, but I also tried deploying to both EKS and GKE clusters in several different configurations to make sure everything was working as expected.

CP-30104: add scout configuration mismatch warnings

---

app/config/validator/deployment.go
app/config/validator/deployment_test.go
app/functions/helmless/default-values.yaml
app/functions/scout/scout.go
app/utils/scout/azure/azure.go
app/utils/scout/azure/azure_test.go
app/utils/scout/scout.go
app/utils/scout/types/types.go
helm/values.yaml

To automatically detect values in AKS
Added an Azure scout.
The cluster name detection is a bit dodgy; the problem is that Azure IMDS provides a single string for both the resource group name and the cluster name: `MC_{resourceGroupName}_{clusterName}_{region}`.
Unfortunately, both resourceGroupName and clusterName can contain underscores, so without knowledge of either parsing is ambiguous. For example, for "MC_foo_bar_baz_qux_useast1", the clusterName could conceivably be bar_baz_qux, baz_qux, or qux.
While Kubernetes clusters *can* include underscores, it is considered best practice to avoid them (generally using dashes instead). Therefore, this scout will assume that the cluster name does *not* contain any underscores. If a cluster name contains underscores, you will need to manually …

CP-30077: add Azure scout

---

app/types/k8s_object.go
helm/templates/webhook-validating-config.yaml
tests/helm/template/cert-manager.yaml
tests/helm/template/federated.yaml
tests/helm/template/manifest.yaml

* https://github.com/Cloudzero/cloudzero-charts/issues/207
Avoiding unnecessary load on the Webhook Server.
Instead of requesting that Kubernetes sends us *all* resources, this requests only the resources we are interested in. This should significantly reduce traffic to the Webhook Server.
Deploy.

CP-30254: explicitly list types we're interested in for admission controller

---

app/domain/diagnostic/k8s/namespace/check.go
app/domain/diagnostic/k8s/namespace/check_test.go
app/domain/diagnostic/k8s/provider/check.go
app/domain/diagnostic/k8s/provider/check_test.go

> The branch name is incorrect
There namespace aware values were not using the right namespace in the validator. We were looking for `NAMESPACE` when we should be looking for `K8S_NAMESPACE`. The confload job does it correctly, but we never updated the validator to use the shared values.
```
│ 2025-07-02T17:08:29Z │ 1.2.2         │ 1.26            │ {'k8s_namespace': {'message': 'the env variable `NAMESPACE` must exist',         │ POD_STARTED  │
│                      │               │                 │ 'passing': False}, 'k8s_provider': {'message': 'the env variable `NAMESPACE`     │              │
│                      │               │                 │ must exist', 'passing': False}, 'k8s_version': {'message': None, 'passing':      │              │
│                      │ …
```

CP-30251: Fix validator environment

---

helm/templates/aggregator-deploy.yaml
tests/helm/template/cert-manager.yaml
tests/helm/template/federated.yaml
tests/helm/template/manifest.yaml

The PVC mount code is not used within the aggregator, so we should remove it incase customers set affinity rules for server and aggregator pods to be placed on the same nodes. If that happens, then both the agent and aggregator pod will request to mount the PVC on the same node, but this is not allowed with the `ReadWriteOnce` PVC request type which is standard for most storage backends.
Related issue: https://cloudzero.atlassian.net/browse/CP-30004

CP-30281: remove unused PVC mount code from the aggregator

---

.dockerignore
Makefile
docker/Dockerfile

Because building images was very slow.
This represents a comprehensive overhaul of the Docker build process to achieve dramatically faster build times, going from 2:30-3:00 minutes down to ~12 seconds.
The optimization consists of several complementary strategies:
* Multi-stage build with platform-specific caching
Each stage uses platform-specific cache mount IDs (e.g., id=apk-$TARGETPLATFORM, id=gomod-$TARGETPLATFORM) to ensure ARM64 and AMD64 builds don't interfere with each other's caches.
* Selective file copying instead of .dockerignore:
Replaced the broad "COPY . ." approach with explicit copying of only the files needed for building (app/ and Makefile). This reduces the build context from ~656kB to ~37kB and eliminates the dependency on .dockerignore patterns.
* Conditional …

CP-30492: optimize Docker build performance

---

.github/dependabot.yml

The thinking is that patches generally come out on Tuesdays, we update our dependencies on Wednesdays, and do a release (if desired) on Thursday.
Change dependabot day from Friday to Wednesday
😇

CP-30738: change dependabot day from Friday to Wednesday

---

.github/workflows/release-to-main.yml

One of the make targets (`helm-generate-tests`) moved (to `helm-test-template`, for consistency with other `helm-test-*` targets), but I forgot to update this workflow.
Replace `helm-generate-tests` with `helm-test-template`
`make helm-test-template`, but the we can really only test the action by running it :(

CP-30788: fix release-to-main action

---

helm/values.yaml
tests/helm/template/cert-manager.yaml
tests/helm/template/federated.yaml
tests/helm/template/manifest.yaml

These are just the dependencies Dependabot can't handle updating for us.
* kubectl 1.33.1 -> 1.33.3
* prometheus-config-reloader 0.83.0 -> 0.84.0
* kube-state-metrics 2.15.0 -> 2.16.0
All three are the latest release
Deploy, make sure nothing breaks horribly.

CP-29639: update KSM, kubectl, and prometheus-config-reloader images

---

app/utils/scout/aws/aws.go
app/utils/scout/aws/aws_test.go
app/utils/scout/detect_configuration_test.go

The CloudZero Agent's AWS scout implementation only supported IMDSv2 for metadata retrieval, which caused failures on clusters that don't have IMDSv2 enabled. This prevented automatic detection of AWS account ID and region, requiring manual configuration in these environments.
Additionally, HTTP 405 errors from the IMDSv2 token endpoint were not providing actionable debugging information, making it difficult for customers to understand why their AWS metadata service calls were failing.
Implemented a graceful fallback mechanism that tries IMDSv2 first, then falls back to IMDSv1 if the token endpoint is unavailable. This maintains security preference for IMDSv2 while providing compatibility with IMDSv1-only environments.
Enhanced error handling to provide specific, actionable error messages …

CP-30974: implement IMDSv1 fallback for AWS metadata retrieval

---

app/utils/scout/google/google.go
app/utils/scout/google/google_test.go

Because we want the project number, not the project ID
Tweak the scout to return the project number
```yaml
apiVersion: batch/v1
kind: Job
metadata:
name: scout-job
namespace: cza
spec:
ttlSecondsAfterFinished: 3600
template:
spec:
restartPolicy: Never
containers:
- name: scout
image: ghcr.io/cloudzero/cloudzero-agent/cloudzero-agent:dev-599b04627281ad4fb8bbdbff63046f7d3ae3d572
command: ["/app/cloudzero-scout", "info"]
resources:
requests:
memory: "64Mi"
cpu: "50m"
limits:
memory: "128Mi"
cpu: "100m"
```
Then `kubectl logs` on the job.

CP-31334: return project *number* not project ID, from scout
